### PR TITLE
goLint: run go generate as part of the linting workflow

### PR DESCRIPTION
**Pull request by marten-seemann**
When using code generators, it is easy to get the repository into an inconsistent state (if one forgets to run `go generate ./...`, for example). This can be very annoying to debug.

We should run `go generate ./...` as part of the linting workflow, and fail if the generated files don't match.

Note that this assumes that the output of code generators is deterministic. This applies to common code generators like the `fmt.Stringer` and gomock.

I've been running something very similar in quic-go for a long time. See https://github.com/quic-go/quic-go/pull/4728 for reference.

---

Sample run: https://github.com/smallstep/bouncer/actions/runs/11946427339/job/33300752473?pr=113.

### CODE REVIEW

**Comment by marten-seemann** [comment]
For `mockgen` in particular, we'll need to invoke it using `go run` (see https://github.com/smallstep/bouncer/pull/114), and add a `tools.go` defining the version (see https://github.com/smallstep/bouncer/pull/106).

We should do a sweep across our repos to make sure they correctly invoke `mockgen` before merging this PR. I'd be happy to do that once we decide to move forward here.

**Review by azazeal — APPROVED** [review]
Thankfully, we don't have generators that take quite a bit of time to complete, so this will work for us (until the point that we do).

**Comment by marten-seemann** [comment]
As far as I can see, this should now work in all repositories. I'm going to merge this PR now. Please let me know if anything breaks.

**Comment by hslatman** [comment]
Had to fix it in https://github.com/smallstep/step-issuer/pull/230 for `controller-gen`.

**Comment by hslatman** [comment]
https://github.com/smallstep/majordomo/pull/85

**Comment by hslatman** [comment]
https://github.com/smallstep/inventory/pull/189

**Pull request merged**
